language: node_js
node_js:
  - 10

install:
  - npm install --prefix app
  - npm install --prefix api

jobs:
  include:
    - stage: App
      script: npm run lint --prefix app
      name: "Lint"
    - script: npm run test:requesthandlers --prefix app
      name: "Unit tests"

    - stage: Api
      script: npm run lint --prefix api
      name: "Lint"

cache: npm

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
