version: '3'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/usr/src
      - /usr/src/node_modules

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/usr/src
      - /usr/src/node_modules

  proxy:
    build:
      context: proxy
      dockerfile: Dockerfile.dev
    volumes:
      - ./proxy:/usr/src
      - /usr/src/node_modules

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile.dev
